version: "3"

services:
  nginx:
    container_name: tg_parser_nginx_server
    image: nginx:latest
    volumes:
      - ./_docker/nginx/logs:/var/log/nginx
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./_docker/php-fpm/www.conf:/etc/php-fpm.d/www.conf
    ports:
      - "8082:80"
    depends_on:
      - php

  php:
    container_name: tg_parser_php_socket
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    volumes:
      - ./:/var/www
      - ./_docker/supervisor/logs:/var/log/supervisor
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7.0.4
    ports:
      - "6372:6379"